services:
  - type: web
    name: tlc-pharmasight-web
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run web:build
    startCommand: node web-server.js & npx serve dist -l 8081
    envVars:
      - key: NODE_VERSION
        value: 18.20.5
      - key: PORT
        value: 8081

