services:
  - type: web
    name: tlc-pharmasight-web
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run render:build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.5
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

